# Generated by Django 4.2 on 2023-04-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('job_ID', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=150)),
                ('dept_head', models.CharField(max_length=150)),
                ('salary_range', models.CharField(max_length=200)),
            ],
        ),
    ]
