# Generated by Django 4.2 on 2023-04-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('proj_id', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=150)),
                ('project_status', models.CharField(max_length=200)),
            ],
        ),
    ]
