# Generated by Django 4.2 on 2023-04-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_id', models.CharField(max_length=200)),
                ('emp_id', models.CharField(max_length=200)),
                ('start_date', models.CharField(max_length=150)),
                ('end_date', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=200)),
            ],
        ),
    ]
