# Generated by Django 4.2 on 2023-04-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(max_length=200),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(max_length=200),
        ),
    ]
