# Generated by Django 4.2 on 2023-04-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0005_alter_leave_end_date_alter_leave_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_id', models.CharField(max_length=200)),
                ('emp_id', models.CharField(max_length=200)),
                ('annual_package', models.DateField(max_length=200)),
                ('package_status', models.DateField(default=False)),
                ('annual_increment', models.CharField(max_length=200)),
            ],
        ),
    ]
