# Generated by Django 4.2 on 2023-04-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0007_remove_salary_package_status_salary_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='payment_status',
            field=models.CharField(max_length=200),
        ),
    ]
