# Generated by Django 4.2 on 2023-04-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0008_alter_salary_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='annual_package',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
