# Generated by Django 4.2 on 2023-05-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0009_alter_salary_annual_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('emp_id', models.CharField(max_length=200)),
            ],
        ),
    ]
